version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: django_backend
    command: ["gunicorn", "--bind", "0.0.0.0:8000", "backend.wsgi:application"]
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=backend.settings

  frontend:
    build:
      context: ./frontend
    container_name: nextjs_frontend
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000

